name: base
dependencies:
  - conda-forge::git

  - conda-forge::python=3.10.4
  - pytorch::pytorch=1.12.0
  - pytorch::cpuonly

  - conda-forge::r-base=4.1
  - conda-forge::r-rcolorbrewer
  - conda-forge::r-tidyverse
  - conda-forge::r-reshape2
  - conda-forge::r-ggpubr
  - conda-forge::r-ggridges
  - conda-forge::r-viridis

  - pip
  - pip:
      - git+https://github.com/mlorthiois/transforkmers.git
