name: annexa
channels:
    - conda-forge
dependencies:
    - r-base=4.0

    - bioconda::bioconductor-bambu=1.0.2
    - bioconda::bioconductor-bsgenome
    - bioconda::bioconductor-deseq2=1.30
    - bioconda::feelnc=0.2
    - bioconda::ucsc-gtftogenepred=377
    - bioconda::ucsc-genepredtobed=377
    - bioconda::samtools=1.12
    - bioconda::rseqc=4.0.0

    - r-pheatmap=1.0
    - r-rcolorbrewer=1
    - r-tidyverse=1.3
    - r-reshape2=1.4
    - r-ggpubr=0.4
    - r-ggridges=0.5
