name: base
dependencies:
  - conda-forge::git

  - conda-forge::python=3.10.4
  - pytorch::pytorch=1.12.0
  - pytorch::cpuonly

  - conda-forge::r-base=4.1
  - conda-forge::r-rcolorbrewer
  - conda-forge::r-tidyverse=1.3.2
  - conda-forge::r-dplyr=1.0.10
  - conda-forge::r-reshape2
  - conda-forge::r-ggpubr
  - conda-forge::r-ggridges
  - conda-forge::r-viridis

  - conda-forge::procps-ng

  - pip
  - pip:
      - git+https://github.com/igdrion/transforkmers.git
      - transformers=4.35.2
      - accelerate=0.24.1
